# This is just a dummy workflow
# But it's a good example of how to setup a workflow which can run TF apply and so on...

name: Setup dummy S3 bucket

on:
  workflow_dispatch:
    inputs:
      webhook_url:
        type: string
        required: true
        description: The webhook URL
      payload:
        type: string
        required: true
        description: The payload to send to the webhook
      port_context:
        type: string
        required: false
        description: The Port context

jobs:
  setup-dummy-s3-bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Setup dummy S3 bucket
        env:
          WEBHOOK_URL: ${{ inputs.webhook_url }}
          PAYLOAD: ${{ inputs.payload }}
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"name": "Port-Demo", "input": '"$PAYLOAD"'}' \
            $WEBHOOK_URL
